# -*- coding: utf-8 -*-
"""data_cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NMv_5N0Gcb8uRLBWiIuD2YfVngD-11uG
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile soil_course/soil_course/data_cleaning.py
# 
# import pandas as pd
# 
# 
# def load_precipitation_data(filename):
# 
#     data = pd.read_excel(filename, skiprows=2)
# 
#     data = data.drop(data.index[3:53], axis=0)
# 
#     data = data.drop(data.columns[1:7], axis=1)
# 
#     data = data.drop(data.columns[11:26], axis=1)
# 
#     data = data.drop([0, 2], axis=0)
# 
#     data = data.drop(
#         data.columns[
#             [x for x in range(11) if x % 2 == 0 and x != 0]
#         ],
#         axis=1
#     )
# 
#     data['anno'] = data['anno'].astype('Int64')
# 
#     return data
# 
# 
# def save_clean_data(data, output_name='dati_puliti.csv'):
# 
#     data.to_csv(output_name, index=False)
# 
#     print(f"Saved file: {output_name}")